<a href="https://colab.research.google.com/github/mike1502/THC/blob/main/Python/NivelIntermedio/Modulos_Y_Bibliotecas/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div style="background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%); padding: 35px 25px; border-radius: 15px; box-shadow: 0 10px 25px rgba(0,0,0,0.15); text-align: center; color: white; margin-bottom: 25px; font-family: 'Outfit', 'Inter', 'Segoe UI', sans-serif;">
  <h1 style="color: #ffffff; font-size: 2.8em; font-weight: 700; margin: 0 0 10px 0; letter-spacing: -1px; text-shadow: 0 2px 4px rgba(0,0,0,0.2);">Numpy</h1>

  
  <div style="border-top: 1px solid rgba(255,255,255,0.18); padding-top: 20px; font-size: 0.95em; color: #cfd8dc; display: flex; justify-content: space-around; flex-wrap: wrap; gap: 15px; font-weight: 500;">

  <div>
    <span style="font-size: 1.5em; font-weight: 800;">Miguel Ángel Carrillo Lucía</span>
    (<a href="mailto:miguelcarrillo15@ciencias.unam.mx" style="font-size: 1.5em; color: #64b5f6; text-decoration: none; font-weight: 600;">miguelcarrillo15@ciencias.unam.mx</a>)
  </div>

  <div>
    <span style="font-size: 1.5em; font-weight: 900;">Karla Elsa Calva Cano</span>
    (<a href="mailto:karla_elsa_@ciencias.unam.mx" style="font-size: 1.5em; color: #64b5f6; text-decoration: none; font-weight: 600;">karla_elsa_@ciencias.unam.mx</a>)
  </div>

</div>

**Objetivo general**

* Aprender los fundamentos de la biblioteca de Numpy

**Objetivos particulares**

* Entender el uso de los métodos de Numpy

[**Regresa al notebook principal**](https://github.com/seismomat/HerramientasComputacionales/blob/main/TemarioDePython/Temario%20de%20Python.ipynb)

<a name='c1'></a>

## Contenido

- [¿Qué es NumPy?](#1)
    - [¿Por qué usar NumPy?](#1-1)
    - [¿Por qué NumPy es más rápido que las listas?](#1-2)
    - [Instalación de Numpy](#1-3)
    - [Importando Numpy](#1-4)
- [Crear un Objeto ndarray de NumPy](#2)
    - [Arreglos 0-D](#2-1)
    - [Arreglos 1-D](#2-2)
    - [Arreglos 2-D](#2-3)
    - [Arreglos 3-D](#2-4)
    - [Checando las dimensiones de los arreglos](#2-5)
    - [Arreglos de dimensión mayor](#2-6)
- [Acceso a elementos](#3)
    - [Arreglos 1-D](#3-1)
    - [Arreglos 2-D](#3-2)
    - [Arreglos 3-D](#3-3)
- [Slicing](#4)
    - [Arreglos 1-D](#4-1)
        - [Paso](#4-1-1)
    - [Arreglos 2-D](#4-2)
- [Buscando en arreglos](#5)
- [Filtrado](#6)
- [Funciones predefinidas de Numpy](#7)

<a name='1'></a>

# ¿Qué es NumPy?
[regresar al contenido](#c1)

NumPy es una biblioteca de Python utilizada para trabajar con matrices.

También tiene funciones para trabajar en el ámbito del álgebra lineal, la transformada de Fourier y las matrices.

NumPy fue creado en 2005 por Travis Oliphant. Es un proyecto de código abierto y puedes utilizarlo libremente.

NumPy significa "Numerical Python" (Python Numérico).

<a name='1-1'></a>

## ¿Por qué usar NumPy?
[regresar al contenido](#c1)

En Python, tenemos listas que cumplen la función de arrays, pero son lentas de procesar.

NumPy tiene como objetivo proporcionar un objeto de array que sea hasta 50 veces más rápido que las listas tradicionales de Python.

El objeto de array en NumPy se llama ndarray y proporciona muchas funciones de soporte que facilitan trabajar con ndarray.

Los arrays se utilizan con mucha frecuencia en la ciencia de datos, donde la velocidad y los recursos son muy importantes.

<a name='1-2'></a>

## ¿Por qué NumPy es más rápido que las listas?
[regresar al contenido](#c1)

Los arrays de NumPy se almacenan en un lugar continuo en la memoria, a diferencia de las listas, por lo que los procesos pueden acceder y manipularlos de manera muy eficiente.

Este comportamiento se llama "localidad de referencia" en informática.

Esta es la razón principal por la que NumPy es más rápido que las listas. Además, está optimizado para funcionar con las últimas arquitecturas de CPU.

<a name='1-3'></a>

## Instalación de Numpy
[regresar al contenido](#c1)

> pip install numpy

<a name='1-4'></a>

## Importando Numpy
[regresar al contenido](#c1)

> import numpy

o también se puede importar con algún alias

> import numpy as np

<a name='2'></a>

# Crear un Objeto ndarray de NumPy
[regresar al contenido](#c1)

`NumPy` se utiliza para trabajar con arrays. El objeto de array en NumPy se llama ndarray.

Podemos crear un objeto ndarray de NumPy utilizando la función `array()`.

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr1 = np.array((1, 2, 3, 4, 5))

print(arr1)

print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


<a name='2-1'></a>

## Arreglos 0-D
[regresar al contenido](#c1)

Los arrays 0-D, o escalares, son los elementos en un array. Cada valor en un array se considera un array 0-D en sí mismo. En otras palabras, un array puede contener múltiples escalares como sus elementos.

In [ ]:
arr = np.array(42)

print(arr)

42


<a name='2-2'></a>

## Arreglos 1-D
[regresar al contenido](#c1)

Un array que tiene arrays 0-D (escalares) como sus elementos se llama array unidimensional o 1-D. En otras palabras, es un array que contiene valores individuales en lugar de secuencias de valores.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


<a name='2-3'></a>

## Arreglos 2-D
[regresar al contenido](#c1)

Un array que tiene arrays 1-D como sus elementos se llama array 2-D.

A menudo se utilizan para representar matrices o tensores de segundo orden.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


<a name='2-4'></a>

## Arreglos 3-D
[regresar al contenido](#c1)

Un array que tiene matrices 2-D como sus elementos se llama array 3-D.

A menudo se utilizan para representar un tensor de tercer orden.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


<a name='2-5'></a>

## Revisando las dimensiones de los arreglos
[regresar al contenido](#c1)

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


<a name='2-6'></a>

## Arreglos de dimensión mayor
[regresar al contenido](#c1)

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


<a name='3'></a>

# Acceso a elementos
[regresar al contenido](#c1)

La indexación de arrays es similar a acceder a un elemento de un array.

Puedes acceder a un elemento de un array haciendo referencia a su número de índice.

Los índices en los arrays de NumPy comienzan en 0, lo que significa que el primer elemento tiene un índice 0, el segundo tiene un índice 1, y así sucesivamente.

<a name='3-1'></a>

## Arreglos 1-D
[regresar al contenido](#c1)

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


<a name='3-2'></a>

## Arreglos 2-D
[regresar al contenido](#c1)

Para acceder a elementos de arrays 2-D, podemos usar enteros separados por comas que representan la dimensión y el índice del elemento.

Piensa en los arrays 2-D como una tabla con filas y columnas, donde la dimensión representa la fila y el índice representa la columna.

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2do elemento de la 1er Fila: ', arr[0, 1])

2do elemento de la 1er Fila:  2


In [ ]:
print('Quinto elemento de la 2da Fila', arr[1, 4])

Quinto elemento de la 2da Fila 10


<a name='3-3'></a>

## Arreglos 3-D
[regresar al contenido](#c1)

Para acceder a elementos de arrays 3-D, podemos usar enteros separados por comas que representan las dimensiones y el índice del elemento. Esto implica especificar la coordenada en cada dimensión para llegar al elemento deseado en el array tridimensional.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


<a name='4'></a>

# Slicing
[regresar al contenido](#c1)

El slicing en Python significa tomar elementos desde un índice dado hasta otro índice dado.

Pasamos el slice en lugar del índice de esta manera: `[inicio:fin]`.

También podemos definir el paso, de esta manera: `[inicio:fin:paso]`.

- Si no especificamos el inicio, se considera 0.
- Si no especificamos el fin, se considera la longitud del array en esa dimensión.
- Si no especificamos el paso, se considera 1.

<a name='4-1'></a>

## Arreglos 1-D
[regresar al contenido](#c1)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7]) #ejemplo

print(arr[1:5])

[2 3 4 5]


In [ ]:
print(arr[4:])

[5 6 7]


In [ ]:
print(arr[:4])

[1 2 3 4]


In [ ]:
print(arr[-3:-1])

[5 6]


<a name='4-1-1'></a>

### Paso
[regresar al contenido](#c1)

> `arreglo[inicio:fin:paso]`

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


<a name='4-2'></a>

## Arreglos 2-D
[regresar al contenido](#c1)

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


<a name='5'></a>

# Buscando en arreglos
[regresar al contenido](#c1)

Puedes buscar un valor específico en un array y obtener los índices que coinciden con ese valor.

Para buscar en un array, utiliza el método `where()`. El método `where()` de NumPy te permite buscar elementos que cumplan con ciertas condiciones y devuelve los índices donde se encuentran esos elementos.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


Existe un método llamado `searchsorted()` que realiza una búsqueda binaria en el array y devuelve el índice donde se insertaría el valor especificado para mantener el orden de búsqueda.

Se asume que el método `searchsorted()` se utiliza en arrays ordenados, ya que se basa en la búsqueda binaria, que funciona eficientemente en datos ordenados.

In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


De forma predeterminada, se devuelve el índice más a la izquierda al buscar un valor en un array, pero podemos especificar `side='right'` para obtener en su lugar el índice más a la derecha.

In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [ ]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


<a name='6'></a>

# Filtrado
[regresar al contenido](#c1)

In [ ]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


<a name='7'></a>

# Funciones predefinidas de numpy
[regresar al contenido](#c1)

**Generación de vectores y mallas.**

| Función        | Propósito                          | Firma básica                                      | Ejemplo                                       |
| :------------- | :--------------------------------- | :------------------------------------------------ | :-------------------------------------------- |
| `np.linspace`  | Puntos equiespaciados por cantidad | `linspace(start, stop, num=50, endpoint=True, …)` | `np.linspace(0, 1, 6)` → `[0., 0.2, …, 1.]`   |
| `np.arange`    | Rango con paso fijo                | `arange(start, stop=None, step=1, …)`             | `np.arange(0, 10, 2)` → `[0 2 4 6 8]`         |
| `np.logspace`  | Puntos en escala log10             | `logspace(start, stop, num=50, base=10.0, …)`     | `np.logspace(0, 3, 4)` → `[1, 10, 100, 1000]` |
| `np.geomspace` | Progresión geométrica              | `geomspace(start, stop, num=50, …)`               | `np.geomspace(1, 1000, 4)`                    |
| `np.meshgrid`  | Rejillas 2D/3D para evaluación     | `meshgrid(x, y, indexing='xy', …)`                | `X, Y = np.meshgrid(x, y)`                    |
| `np.mgrid`     | Rango tipo rejilla densa           | `mgrid[xmin:xmax:Nj, …]`                          | `X, Y = np.mgrid[-1:1:5j, -2:2:5j]`           |
| `np.ogrid`     | Rango tipo rejilla perezosa        | `ogrid[xmin:xmax:step, …]`                        | `X, Y = np.ogrid[-1:1:0.5, -2:2:0.5]`         |


**Constructores.**

| Función    | Propósito                     | Firma básica                          | Ejemplo              |
| :--------- | :---------------------------- | :------------------------------------ | :------------------- |
| `np.zeros` | Inicializa con ceros          | `zeros(shape, dtype=float)`           | `np.zeros((3,3))`    |
| `np.ones`  | Inicializa con unos           | `ones(shape, dtype=float)`            | `np.ones(5)`         |
| `np.full`  | Inicializa con un valor fijo  | `full(shape, fill_value, dtype=None)` | `np.full((2,2), 7.)` |
| `np.eye`   | Matriz identidad              | `eye(N, M=None, k=0, dtype=float)`    | `np.eye(3)`          |
| `np.diag`  | Diagonaliza o extrae diagonal | `diag(v, k=0)`                        | `np.diag([2,3,4])`   |
| `np.empty` | Arreglo sin inicializar       | `empty(shape, dtype=float)`           | `np.empty((2,3))`    |


**Forma y apilado**

| Función                 | Propósito                     | Firma básica                  | Ejemplo                      |
| :---------------------- | :---------------------------- | :---------------------------- | :--------------------------- |
| `np.reshape`            | Cambia forma sin copiar datos | `reshape(a, newshape)`        | `a.reshape(3,4)`             |
| `np.ravel`              | Aplana vista 1D               | `ravel(a)`                    | `A.ravel()`                  |
| `np.squeeze`            | Elimina ejes de tamaño 1      | `squeeze(a, axis=None)`       | `np.squeeze(a)`              |
| `np.newaxis`            | Agrega eje                    | `a[:, np.newaxis]`            | `a[:, np.newaxis] → 12×1`    |
| `np.concatenate`        | Une a lo largo de un eje      | `concatenate(seq, axis=0)`    | `np.concatenate([u, v])`     |
| `np.stack`              | Apila creando nuevo eje       | `stack(seq, axis=0)`          | `np.stack([u, v])`           |
| `np.hstack / np.vstack` | Apila horizontal o vertical   | `hstack(tup)` / `vstack(tup)` | `np.hstack([u, v])`          |
| `np.block`              | Construye por bloques         | `block(blocks)`               | `np.block([[I, D], [D, I]])` |


**Indexado y selección.**
| Función             | Propósito                  | Firma básica                     | Ejemplo                                   |
| :------------------ | :------------------------- | :------------------------------- | :---------------------------------------- |
| *Indexado booleano* | Filtrado por condición     | `a[cond]`                        | `x[x%2==0]`                               |
| `np.where`          | Selección condicional      | `where(cond, x, y)`              | `np.where(x<5, x, -1)`                    |
| `np.unique`         | Valores únicos y conteos   | `unique(a, return_counts=False)` | `u, c = np.unique(a, return_counts=True)` |
| `np.bincount`       | Conteo por bins de enteros | `bincount(x, weights=None)`      | `np.bincount([1,1,2,3])`                  |
| `np.argsort`        | Índices de ordenamiento    | `argsort(a)`                     | `idx = np.argsort(a)`                     |
| `np.argpartition`   | Top-k parcial eficiente    | `argpartition(a, kth)`           | `idx = np.argpartition(a, -3)[-3:]`       |


**Álgebra Lineal.**

| Función               | Propósito                      | Firma básica               | Ejemplo                       |
| :-------------------- | :----------------------------- | :------------------------- | :---------------------------- |
| `A @ B` / `np.matmul` | Producto matricial             | `A @ B`                    | `A @ B`                       |
| `np.linalg.solve`     | Resuelve `Ax=b`                | `linalg.solve(A, b)`       | `x = np.linalg.solve(A, b)`   |
| `np.linalg.eig`       | Autovalores y autovectores     | `linalg.eig(A)`            | `w, V = np.linalg.eig(A)`     |
| `np.linalg.svd`       | Descomp. en valores singulares | `linalg.svd(A)`            | `U, s, Vh = np.linalg.svd(A)` |
| `np.linalg.norm`      | Normas vectoriales/matriciales | `linalg.norm(x, ord=None)` | `np.linalg.norm(x)`           |
| `np.linalg.det`         | Determinante                           | `linalg.det(A)`                 | `np.linalg.det(A)`                          |
| `np.linalg.inv`         | Inversa (no recomendada para resolver) | `linalg.inv(A)`                 | `A_inv = np.linalg.inv(A)`                  |
| `np.linalg.pinv`        | Pseudoinversa de Moore-Penrose         | `linalg.pinv(A, rcond=…)`       | `A_p = np.linalg.pinv(A)`                   |
| `np.linalg.lstsq`       | Mínimos cuadrados (`Ax≈b`)             | `lstsq(A, b, rcond=…)`          | `x, *_ = np.linalg.lstsq(A, b, rcond=None)` |
| `np.linalg.matrix_rank` | Rango matricial                        | `matrix_rank(A, tol=None)`      | `np.linalg.matrix_rank(A)`                  |
| `np.linalg.cond`        | Número de condición                    | `cond(A, p=None)`               | `np.linalg.cond(A)`                         |
| `np.linalg.qr`          | Descomposición QR                      | `qr(A, mode='reduced')`         | `Q, R = np.linalg.qr(A)`                    |
| `np.linalg.cholesky`    | Cholesky (A SPD)                       | `cholesky(A)`                   | `L = np.linalg.cholesky(A)`                 |
| `np.linalg.eigh`        | Autovalores/vec. simétricos            | `eigh(A)`                       | `w, V = np.linalg.eigh(S)`                  |
| `np.outer`              | Producto externo                       | `outer(x, y)`                   | `np.outer(u, v)`                            |
| `np.inner`              | Producto interno                       | `inner(x, y)`                   | `np.inner(u, v)`                            |
| `np.kron`               | Producto de Kronecker                  | `kron(A, B)`                    | `np.kron(A, B)`                             |
| `np.tensordot`          | Contracción de ejes                    | `tensordot(a, b, axes=…)`       | `np.tensordot(A, B, axes=1)`                |
| `np.einsum`             | Einstein sum (flexible/rápido)         | `einsum(subscripts, *operands)` | `np.einsum('ij,jk->ik', A, B)`              |
| `np.trace`              | Traza (suma diagonal)                  | `trace(A, offset=0)`            | `np.trace(A)`                               |


**Análisis de señales. Transformada de Fourier.**

| Función                     | Propósito              | Firma básica           | Ejemplo                          |
| :-------------------------- | :--------------------- | :--------------------- | :------------------------------- |
| `np.fft.fft / ifft`         | FFT compleja e inversa | `fft(a)` / `ifft(A)`   | `A = np.fft.fft(a)`              |
| `np.fft.rfft / irfft`       | FFT real e inversa     | `rfft(a)` / `irfft(A)` | `Ar = np.fft.rfft(a)`            |
| `np.fft.fftfreq / rfftfreq` | Vector de frecuencias  | `fftfreq(n, d=1.0)`    | `f = np.fft.rfftfreq(N, d=1/fs)` |


**Aleatoriedad.**

| Función                 | Propósito               | Firma básica                  | Ejemplo                            |
| :---------------------- | :---------------------- | :---------------------------- | :--------------------------------- |
| `np.random.default_rng` | Crea generador moderno  | `default_rng(seed=None)`      | `rng = np.random.default_rng(123)` |
| `rng.integers`          | Enteros aleatorios      | `integers(low, high, size)`   | `rng.integers(0, 10, size=5)`      |
| `rng.normal`            | Distribución normal     | `normal(loc, scale, size)`    | `rng.normal(0, 1, 1000)`           |
| `rng.uniform`           | Uniforme continua       | `uniform(low, high, size)`    | `rng.uniform(-1, 1, 4)`            |
| `rng.choice`            | Muestreo de poblaciones | `choice(a, size, replace, p)` | `rng.choice([0,1,2], size=4)`      |


**Entrada y salida.**

| Función             | Propósito                      | Firma básica                          | Ejemplo                                     |
| :------------------ | :----------------------------- | :------------------------------------ | :------------------------------------------ |
| `np.loadtxt`        | Carga texto/CSV (simple)       | `loadtxt(fname, delimiter, dtype)`    | `np.loadtxt('datos.csv', delimiter=',')`    |
| `np.genfromtxt`     | Carga tolerante a faltantes    | `genfromtxt(fname, delimiter, dtype)` | `np.genfromtxt('datos.csv', delimiter=',')` |
| `np.savetxt`        | Guarda a texto/CSV             | `savetxt(fname, X, fmt, delimiter)`   | `np.savetxt('out.csv', X, delimiter=',')`   |
| `np.save / np.load` | Guarda/carga en binario `.npy` | `save(file, arr)` / `load(file)`      | `np.save('a.npy', a); np.load('a.npy')`     |


**Estadística.**

| Función                 | Propósito             | Firma básica                                                 | Ejemplo                    |
| :---------------------- | :-------------------- | :----------------------------------------------------------- | :------------------------- |
| `np.sum`                | Suma de elementos     | `sum(a, axis=None, dtype=None, keepdims=False, where=None)`  | `np.sum(A, axis=0)`        |
| `np.prod`               | Producto de elementos | `prod(a, axis=None, dtype=None, keepdims=False, where=None)` | `np.prod(x)`               |
| `np.mean`               | Promedio              | `mean(a, axis=None, dtype=None, keepdims=False, where=None)` | `np.mean(A, axis=1)`       |
| `np.median`             | Mediana               | `median(a, axis=None, keepdims=False)`                       | `np.median(x)`             |
| `np.std`                | Desviación estándar   | `std(a, axis=None, ddof=0, keepdims=False)`                  | `np.std(x, ddof=1)`        |
| `np.var`                | Varianza              | `var(a, axis=None, ddof=0, keepdims=False)`                  | `np.var(x)`                |
| `np.min / np.max`       | Mínimo / Máximo       | `min(a, axis=None, keepdims=False)` / `max(...)`             | `np.max(A, axis=0)`        |
| `np.argmin / np.argmax` | Índice del min / max  | `argmin(a, axis=None)` / `argmax(...)`                       | `np.argmax(x)`             |
| `np.quantile`           | Cuantiles (0–1)       | `quantile(a, q, axis=None, keepdims=False)`                  | `np.quantile(x, 0.9)`      |
| `np.percentile`         | Percentiles (0–100)   | `percentile(a, q, axis=None, keepdims=False)`                | `np.percentile(x, 90)`     |
| `np.average`            | Media ponderada       | `average(a, axis=None, weights=None, returned=False)`        | `np.average(x, weights=w)` |
| `np.cumsum`             | Suma acumulada        | `cumsum(a, axis=None, dtype=None)`                           | `np.cumsum(x)`             |
| `np.cumprod`            | Producto acumulado    | `cumprod(a, axis=None, dtype=None)`                          | `np.cumprod(x)`            |


**NaN**

| Función                 | Propósito                       | Firma básica                                           | Ejemplo                   |
| :---------------------- | :------------------------------ | :----------------------------------------------------- | :------------------------ |
| `np.nansum`             | Suma ignorando `NaN`            | `nansum(a, axis=None, dtype=None, keepdims=False)`     | `np.nansum(x)`            |
| `np.nanprod`            | Producto ignorando `NaN`        | `nanprod(a, axis=None, dtype=None, keepdims=False)`    | `np.nanprod(x)`           |
| `np.nanmean`            | Media ignorando `NaN`           | `nanmean(a, axis=None, dtype=None, keepdims=False)`    | `np.nanmean(A, axis=1)`   |
| `np.nanmedian`          | Mediana ignorando `NaN`         | `nanmedian(a, axis=None, keepdims=False)`              | `np.nanmedian(x)`         |
| `np.nanstd / np.nanvar` | Desv. est./var. ignorando `NaN` | `nanstd(a, ...)` / `nanvar(a, ...)`                    | `np.nanstd(x)`            |
| `np.nanmin / np.nanmax` | Min/Max ignorando `NaN`         | `nanmin(a, axis=None, keepdims=False)` / `nanmax(...)` | `np.nanmax(A, axis=0)`    |
| `np.nanquantile`        | Cuantiles ignorando `NaN`       | `nanquantile(a, q, axis=None, keepdims=False)`         | `np.nanquantile(x, 0.95)` |
